### ISSUE TITLE
파일 이름 컨벤션

### ISSUE THREAD

**Issue by youjmen** [DSM-DMS/PMS_Android_v1#3]
![image](https://user-images.githubusercontent.com/48317457/98434000-1b3ada80-210f-11eb-9ea7-705bcccde668.png)

**Comment by youjmen** [comment]
단어마다 대문자로 통일좀;; 예) PasswordActivty, CodeDialogFragment
고쳐야 할 것 : passwordActivity, CodeDialog_Fragment

**Comment by dlswer23** [comment]
현재 CodeDialog와 passwordActivity는 파일 삭제? 되어 아직 수정하지 못했습니다

**Comment by dlswer23** [comment]
잘못된 파일명 수정 했습니다.
